baseurl: /MarkTang.github.io

highlighter: rouge

theme: jekyll-theme-cayman

markdown: redcarpet

safe: false

pygments: true

excerpt_separator: "\n\n\n"

paginate: 5

author:             
  name: MarkTang
  email: marktangwao@foxmail.com
  link: marktangwao
  
title: MarkTang's Blog



